WIP: [BOSS-624] Remove dependencies from headers for AirBoss linux build
airmap/image-processing pull request #12
Opened 2021-04-14 03:01 UTC by bluecamel

2021-04-14 15:55 UTC, remster commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<cv::Mat> calibration_intrinsics;
you can keep boost optional - it's header only

2021-04-14 16:01 UTC, remster commented
Its a little hard to work out what was the problem and what's then the solution - can you give a reviewer a hand pls? Why did Airboss need to include headers (what headers) that forced it to link boost and opencv?

2021-04-14 16:29 UTC, bluecamel commented
> Its a little hard to work out what was the problem and what's then the solution - can you give a reviewer a hand pls? Why did Airboss need to include headers (what headers) that forced it to link boost and opencv?

The main problem was that I added monitoring/estimation without worrying about the OpenCV dependencies, as I thought that we were okay with linking to OpenCV in AirBoss.  Since there are base classes that are are used in both the "full version" (stand alone executable, AirBoss Android) and the outprocess stitcher (AirBoss Linux), I had to separate things such that AirBoss Linux could include the headers that it needs for the outprocess stitcher without the OpenCV dependency.

The main include for AirBoss linux is `airmap/stitcher.h`, which includes:
- `airmap/camera.h`
- `airmap/logging.h`
- `airmap/monitor/estimator.h`
- `airmap/monitor/monitor.h`
- `airmap/panorama.h`

2021-04-14 16:33 UTC, keith-bennett-airmap requested changes

2021-04-14 16:33 UTC, keith-bennett-airmap commented on stitcher/include/airmap/images.h
> +               int interpolation = InterpolationFlags::INTER_LINEAR_EXACT);
To fix the forward declaration issue you can have a static function that returns the default value, such as

```
static InterpolationFlags default_interpolation_flags(); // definition in the .cpp
void scale(double scale, InterpolationFlags interpolation = default_interpolation_flags());
```

You should also prefer to use the name of the enumeration type instead of a plain `int` whenever possible.

2021-04-14 16:33 UTC, keith-bennett-airmap commented on stitcher/include/airmap/monitor/estimator.h
> +            const std::shared_ptr<Camera> camera,
More `boost::optional` vs `std::shared_ptr`

2021-04-14 16:33 UTC, keith-bennett-airmap commented on stitcher/test/gtest/monitor/estimator.cpp
> +    std::shared_ptr<Camera> cameraVesper;
Do these need to be `shared_ptr`?

2021-04-14 16:33 UTC, keith-bennett-airmap commented on stitcher/src/opencv/forward.cpp
> +// TODO(bkd): should be cv::InputOutputArray
`TODO`

2021-04-14 16:33 UTC, keith-bennett-airmap commented on stitcher/include/airmap/distortion.h
>  using boost::filesystem::path;
You haven't removed `boost/filesystem.hpp` or `boost/format.hpp` in this header. This dependency can be reached in AirBoss via `#include <airmap/stitcher.h>` -> `camera.h` -> `distortion.h` -> `boost/filesystem.hpp`.

You're also `using boost::filesystem::path` still.

2021-04-15 18:40 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<cv::Mat> calibration_intrinsics;
The main reason for switching away from `boost::optional` is that `cv::Mat` is forward declared, and is an incomplete type here.  I'm definitely open to alternatives.  This just seemed like a straight forward way to get similar functionality.

2021-04-15 18:49 UTC, bluecamel commented on stitcher/include/airmap/opencv/forward.h
> +enum GraphCutSeamFinderCostType { COST_COLOR, COST_COLOR_GRAD };
I tried to do this, but couldn't get it to work.  Here's the error:

```[build] In file included from ../src/distortion.cpp:4:
[build] /usr/local/include/opencv4/opencv2/imgproc.hpp:244:6: error: enumeration previously declared with fixed underlying type
[build] enum InterpolationFlags{
[build]      ^
[build] ../include/airmap/opencv/forward.h:5:6: note: previous declaration is here
[build] enum InterpolationFlags : int;```

I think that it's because OpenCV doesn't declare with a specific type, but not sure if there's a way around it.  I'd definitely rather that than have to maintain these going forward.

2021-04-15 18:51 UTC, bluecamel commented on stitcher/include/airmap/opencv/forward.h
> +// TODO(bkd): should be cv::InputOutputArray
[Fixed](https://github.com/airmap/image-processing/pull/12/commits/587d2c557cacdf60c58f5ceef772b30f97fd4015).

Thanks! :pray:

2021-04-15 18:51 UTC, bluecamel commented on stitcher/src/opencv/forward.cpp
> +// TODO(bkd): should be cv::InputOutputArray
[Fixed](https://github.com/airmap/image-processing/pull/12/commits/587d2c557cacdf60c58f5ceef772b30f97fd4015).

Thanks! :pray:

2021-04-15 18:52 UTC, bluecamel commented on stitcher/include/airmap/distortion.h
>  using boost::filesystem::path;
This was actually because I had the includes in the wrong place.  [Fixed here](https://github.com/airmap/image-processing/pull/12/commits/26d3625b4fcbce0f7030ea8397db8200526d105c).

2021-04-15 18:53 UTC, bluecamel commented on stitcher/include/airmap/camera_models.h
> +        return nullptr;
[Fixed](https://github.com/airmap/image-processing/pull/12/commits/587d2c557cacdf60c58f5ceef772b30f97fd4015).

Thanks! :pray:

2021-04-15 19:24 UTC, keith-bennett-airmap commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<cv::Mat> calibration_intrinsics;
`std::unique_ptr<cv::Mat>` should be compatible with forward-declared types.

2021-04-15 19:38 UTC, bluecamel commented on stitcher/include/airmap/images.h
> +               int interpolation = InterpolationFlags::INTER_LINEAR_EXACT);
[Done](https://github.com/airmap/image-processing/pull/12/commits/1217a77001308252ce644b62509da4c9a0db3778).

2021-04-15 19:39 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<Impl> _impl;
Done.

2021-04-15 19:43 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +        std::shared_ptr<DistortionModel> _distortion_model = nullptr,
Well, I definitely don't have much experience here and am likely missing something, but I haven't been able to do this.  Since the `Camera` pointer is shared (which is actually shared between a couple of objects), I get compilation errors when making these unique (since the copy constructor is implicitly deleted).  Am I missing something there? (probably)

2021-04-15 20:21 UTC, keith-bennett-airmap commented on stitcher/include/airmap/opencv/forward.h
> +enum GraphCutSeamFinderCostType { COST_COLOR, COST_COLOR_GRAD };
Ack, you're right! I thought opencv had a storage specifier. WIthout it, it can't be forward decl'd.

2021-04-15 20:22 UTC, keith-bennett-airmap commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<Impl> _impl;
Is it? I still see it as shared_ptr

It's not a big deal

2021-04-15 20:33 UTC, keith-bennett-airmap commented on stitcher/include/airmap/camera.h
> +        std::shared_ptr<DistortionModel> _distortion_model = nullptr,
`unique_ptr` and `shared_ptr` have different lifetime guarantees. Whoever "owns" the Camera should be the authority in the lifetime of the pointed-to object. Lifetimes of objects are an important consideration in C++ since there is no garbage collection. But as long as there's no circular dependencies with the shared pointers then it'll be fine, just not as efficient.

There aren't circular dependencies -- `Camera`'s only ownership is of an `Impl` and `Impl` doesn't own any pointers. So it'll be fine, just not as efficient as it could be. It shouldn't block the merge

2021-04-15 20:33 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<cv::Mat> calibration_intrinsics;
Oh, I was explaining why I moved away from `boost::optional`.  My challenge using `unique_ptr` vs `shared_ptr` is a [separate issue](AirBossMissionPlanner-2.3.5-11-ge8a23ef2a-x86_64.AppImage).  I'm trying to figure out a way to do that, but no luck yet :smile:

2021-04-15 20:35 UTC, keith-bennett-airmap commented on stitcher/include/airmap/distortion.h
>  using boost::filesystem::path;
That header isn't chained in any include from AirBoss so I'd consider it an internal-only header. But it's still visible to AirBoss because it's under `include/` which gets copied into AirBoss. It's not important since it's not reached by AirBoss any more but for cleanliness it should be moved into `src/` so that it doesn't even get installed into and pollute AirBoss

2021-04-15 20:36 UTC, keith-bennett-airmap approved these changes

2021-04-15 20:41 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +        std::shared_ptr<DistortionModel> _distortion_model = nullptr,
Here's the error:

```[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/shared_ptr.h:706:19: note: in instantiation of function template specialization 'std::allocate_shared<airmap::stitcher::Camera, std::allocator<airmap::stitcher::Camera>, const airmap::stitcher::Camera &>' requested here
[build]       return std::allocate_shared<_Tp>(std::allocator<_Tp_nc>(),
[build]                   ^
[build] ../include/airmap/camera_models.h:30:29: note: in instantiation of function template specialization 'std::make_shared<airmap::stitcher::Camera, const airmap::stitcher::Camera &>' requested here
[build]                 return std::make_shared<Camera>(model.second);
[build]                             ^
[build] ../include/airmap/camera.h:57:38: note: copy constructor of 'Camera' is implicitly deleted because field 'distortion_model' has a deleted copy constructor
[build]     std::unique_ptr<DistortionModel> distortion_model;
[build]                                      ^
[build] /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/unique_ptr.h:383:7: note: 'unique_ptr' has been explicitly marked deleted here
[build]       unique_ptr(const unique_ptr&) = delete;```

2021-04-15 20:41 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +    std::shared_ptr<Impl> _impl;
Whoops, I'm sorry, this is not done, for the [same reason as the others](https://github.com/airmap/image-processing/pull/12#discussion_r614345015).

2021-04-15 20:46 UTC, bluecamel commented on stitcher/include/airmap/camera.h
> +        std::shared_ptr<DistortionModel> _distortion_model = nullptr,
Oh, I hadn't refreshed before adding that comment and just saw yours.  I'm getting somewhat up to speed on the differences and understand that it will inefficiently increment and decrement reference counts.  I've seen some folks saying that it's potentially hundreds of times slower, which is a bummer.

Since you approved and Aleksey is waiting, I'll merge this, but add this to the list of things to learn on weekends. :smile:

2021-04-15 20:47 UTC, merged