BOSS-328: Fixes for logging and Android build.
airmap/image-processing pull request #8
Opened 2021-02-02 08:58 UTC by bluecamel

2021-02-04 18:26 UTC, jennerl commented on stitcher/include/airmap/panorama.h
> + * is used in
used in ... ?

2021-02-04 18:41 UTC, jennerl commented on stitcher/include/airmap/opencv_stitcher.h
>  using boost::filesystem::path;
wasn't one of the goals to remove boost dependency? Sorry if this is off base, just going from recollection

2021-02-04 18:49 UTC, jennerl approved these changes

2021-02-04 19:48 UTC, bluecamel commented on stitcher/include/airmap/opencv_stitcher.h
>  using boost::filesystem::path;
oof, I'm sorry.  I forgot to remove this once I got boost linked for Android.  I've removed the `airmap::filesystem` namespace again.

2021-02-04 19:49 UTC, bluecamel commented on stitcher/include/airmap/panorama.h
> + * is used in
Sorry, this namespace has been removed now.

2021-02-12 00:35 UTC, keith-bennett-airmap requested changes

2021-02-12 00:35 UTC, keith-bennett-airmap commented on stitcher/include/airmap/stitcher.h
> +        _retries = 0;
Why does `cancel()` set `_retries`?

2021-02-12 00:35 UTC, keith-bennett-airmap commented on stitcher/src/panorama.cpp
> +        _path = _path.substr(0, _path.size() - 1);
[`std::string::substr()`](https://en.cppreference.com/w/cpp/string/basic_string/substr) will return a new string which means this may allocate a temporary. The temporary will be assigned to `_path` which will then deallocate the string it was originally assigned in the initialization list.

You could use [`_path.erase()`](https://en.cppreference.com/w/cpp/string/basic_string/erase) or [`_path.resize()`](https://en.cppreference.com/w/cpp/string/basic_string/resize) instead. Then you won't allocate a temporary and all will be well.

2021-02-12 00:35 UTC, keith-bennett-airmap commented on stitcher/src/panorama.cpp
> +        return path("");
It's better to [return `{}`](https://stackoverflow.com/a/39487231/1111557) instead of a `path("")`. It's not significantly so but it's worth understanding that [a different (less-optimal) constructor is used](https://stackoverflow.com/a/11556468/1111557).

2021-02-12 00:35 UTC, keith-bennett-airmap commented on stitcher/src/panorama.cpp
> +    return result.substr(0, result.find_last_of("."));
If the last slash is found then you're allocating an unnecessary temporary. If the last slash isn't found then you're calling `find_last_of()` again but with a dot instead. If the dot isn't found (eg, in an empty path) then you effectively call `substr(0, -1)` which will do Bad Things.

2021-02-12 15:45 UTC, bluecamel commented on stitcher/include/airmap/panorama.h
> + * if only using headers.
[Removed](https://github.com/airmap/image-processing/pull/8/commits/f18bbc7ca2173bf16309b36b9b8da7fe768a0f42).

2021-02-12 15:48 UTC, bluecamel commented on stitcher/include/airmap/stitcher.h
> +        _retries = 0;
This (and the following changes commented on) were Remek's original code that I had tried to remove and then pulled back in.

My understanding of this is that, even though the underlying stitcher is also cancelled, this keeps `RetryingStitcher::stitch` from calling the underlying stitch again.

2021-02-12 17:09 UTC, bluecamel commented on stitcher/src/panorama.cpp
> +        return path("");
I think I've [fixed this](https://github.com/airmap/image-processing/pull/8/commits/678087403820e6b9bfbdd6ca050dfdff0345cc1c).

2021-02-12 17:09 UTC, bluecamel commented on stitcher/src/panorama.cpp
> +    return result.substr(0, result.find_last_of("."));
I think I've [fixed this](https://github.com/airmap/image-processing/pull/8/commits/678087403820e6b9bfbdd6ca050dfdff0345cc1c).

2021-02-12 19:34 UTC, keith-bennett-airmap commented on stitcher/src/panorama.cpp
> +    return result.substr(0, result.find_last_of("."));
I still don't think this does what you want. Or, if it does, then it's not doing what I would expect for [a standard `stem()` filesystem operation](https://en.cppreference.com/w/cpp/filesystem/path/stem).

I don't want to spend a lot of time bikeshedding on it. Please feel free to correct me or perhaps write a simple unit test to exercise it and demonstrate it.

Here's what I came up with which demonstrate my misunderstanding
```
#include "gtest/gtest.h"
#include "airmap/panorama.h"
TEST(airmap_path, stem)
{
    using path = airmap::filesystem::path;
    {
        path p;
        EXPECT_EQ(p.stem(), "");
    }
    {
        path p{"foo"};
        EXPECT_EQ(p.stem(), "foo");
    }
    {
        path p{"/foo"};
        EXPECT_EQ(p.stem(), "foo");
    }
    {
        path p{"/foo.bar"};
        EXPECT_EQ(p.stem(), "foo");
    }
    {
        path p{"/foo/bar"};
        EXPECT_EQ(p.stem(), "bar");
    }
    {
        path p{"/foo/.bar"};
        EXPECT_EQ(p.stem(), ".bar");
    }
    {
        path p{"foo.bar.baz"};
        EXPECT_EQ(p.stem(), "foo.bar");
    }
}
```

2021-02-12 19:58 UTC, bluecamel commented on stitcher/src/panorama.cpp
> +    return result.substr(0, result.find_last_of("."));
I agree that it doesn't cover everything that boost or other `stem` operations do.  I was attempting to resolve the bigger issues that you called out without expanding scope.  I know that Remek's original code has always worked for the standard use cases and I confirmed this change with that as well.  @remster may have input here.

I'm currently thinking that I'll take this on this weekend since I don't want to keep delaying progress on other things.

2021-02-13 02:52 UTC, bluecamel commented on stitcher/src/panorama.cpp
> +    return result.substr(0, result.find_last_of("."));
[Improvements](https://github.com/airmap/image-processing/pull/8/commits/72239df8c7c98f94423d896eab1badb03ba36ff2).

2021-03-10 03:23 UTC, keith-bennett-airmap approved these changes
I'm sorry I missed the notifications about this branch and it got lost behind other tickets. Are the changes here still relevant? It builds and tests clean on my machine except for the two tests that also fail on master

2021-03-10 03:23 UTC, keith-bennett-airmap commented on stitcher/include/airmap/panorama.h
> +            return L".";
I'm fairly sure that `L"."` translates to `std::wstring`. Have you tested `_WIN32`? I don't think Windows support isn't on our roadmap so having this broken shouldn't be too big of a deal/

2021-03-23 21:32 UTC, merged